name: 赞助模板
description: 自助添加赞助
body:
  - type: textarea
    id: config-file
    validations:
      required: true
    attributes:
      label: 赞助信息
      value: |
        ```json
        {
            "name": "",
            "avatar": "",
            "date": "",
            "money": ""
        }
        ```