name: 赞助模板
description: 自助添加赞助
body:
  - type: input
    id: name
    attributes:
      label: name
      description: name
  - type: input
    id: avatar
    attributes:
      label: avatar
      description: avatar
  - type: input
    id: date
    attributes:
      label: date
      description: date
  - type: input
    id: money
    attributes:
      label: money
      description: money
