name: Process Donation Issue

on:
  issues:
    types: [opened]

jobs:
  process-donation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: output
          fetch-depth: 0
          
      - name: Get issue form data
        id: get-issue-data
        run: |
          # Get form data from issue event
          NAME='${{ github.event.issue.body }}' | grep -oP '(?<=### name\s*\n)[^\n]*'
          AVATAR='${{ github.event.issue.body }}' | grep -oP '(?<=### avatar\s*\n)[^\n]*'
          DATE='${{ github.event.issue.body }}' | grep -oP '(?<=### date\s*\n)[^\n]*'
          MONEY='${{ github.event.issue.body }}' | grep -oP '(?<=### money\s*\n)[^\n]*'
          
          # Create JSON object
          JSON_DATA=$(jq -n \
            --arg name "$NAME" \
            --arg avatar "$AVATAR" \
            --arg date "$DATE" \
            --arg money "$MONEY" \
            '{name: $name, avatar: $avatar, date: $date, money: $money}')
            
          echo "Generated JSON data: $JSON_DATA"
          echo "json_data=$JSON_DATA" >> $GITHUB_OUTPUT
          
      - name: Read existing donate.json
        id: read-donate
        run: |
          if [ -f "donate.json" ]; then
            EXISTING_DATA=$(cat donate.json | jq -c '.' 2>/dev/null || echo "[]")
            echo "existing_data=$EXISTING_DATA" >> $GITHUB_OUTPUT
          else
            echo "existing_data=[]" >> $GITHUB_OUTPUT
          fi
          
      - name: Update donate.json
        run: |
          # Combine existing data with new data
          UPDATED_DATA=$(echo '${{ steps.read-donate.outputs.existing_data }}' | jq --argjson new "${{ steps.get-issue-data.outputs.json_data }}" '. += [$new]')
          echo "$UPDATED_DATA" > donate.json
          # Format JSON
          jq '.' donate.json > temp.json && mv temp.json donate.json
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add donate.json
          git commit -m "Add donation from issue #${{ github.event.issue.number }}"
          git push